name: Prettier format

on:
 workflow_dispatch:

jobs:
 check:
  name: Check Format
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    language: ["javascript"]
    node: ["18.x"]
  steps:
   - name: 🧱 Checkout repository
     uses: actions/checkout@v3
   - name: 🔩 Setup PNPM
     uses: pnpm/action-setup@v2
     with:
      version: latest
   - name: 🔩 Setup Node ${{ matrix.node }}
     uses: actions/setup-node@v3
     with:
      node-version: ${{ matrix.node }}
      cache: "pnpm"
   - name: 🚀 Install dependencies
     run: pnpm install
   - name: "🚀 Format code"
     run: "pnpm run format"
   - name: "🚀 Commit formatted code"
     uses: stefanzweifel/git-auto-commit-action@v4
     with:
      commit_message: "[🚀] Code formatting"
      branch: ${{ github.head_ref }}
      commit_user_name: IgorKowalczykBot
      commit_user_email: "igor.kowalczyk.bot@onet.pl"
